backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/PostController.php
<?php

namespace frontend\controllers;

use frontend\models\Post;
use frontend\models\PostContent;
use yii\web\Controller;

class PostController extends Controller
{
    public function actionIndex($id)
    {
        $post = Post::find()->select(
            [
                'post.id',
                'post.author_id',
                'post.title',
                'post.short_description',
                'post.read_time',
                'post.img',
                'post.create_time',
                'post.update_time',
                'post.post_meta',
                'post.status',
                'author.author_name',
                'author.author_pic',
                'author.author_meta',
            ])->where(['post.id' => $id])->leftJoin('author', 'author.id = post.author_id')->all();

        $post_content = PostContent::find()->select(
            [
                'post_content.id',
                'post_content.post_id',
                'post_content.content',
                'post_content.type',
                'post_content.label',
                'post_content.image',
            ]
        )->where(['post_content.post_id' => $id])->orderBy(['id' => SORT_ASC])->all();

        $side_post = Post::find()->select(
            [
                'post.id',
                'post.author_id',
                'post.title',
                'post.short_description',
                'post.read_time',
                'post.img',
                'post.create_time',
                'post.update_time',
                'post.post_meta',
                'post.status',
                'author.author_name',
                'author.author_pic',
                'author.author_meta',
            ])->where(['post.status' => 0])->andWhere(['!=', 'post.id', $id])->orderBy(['post.create_time' => SORT_DESC])->leftJoin('author', 'author.id = post.author_id')->limit(3)->all();

        $top_post = Post::find()->select(
            [
                'post.id',
                'post.author_id',
                'post.title',
                'post.short_description',
                'post.read_time',
                'post.img',
                'post.create_time',
                'post.update_time',
                'post.post_meta',
                'post.status',
                'author.author_name',
                'author.author_pic',
                'author.author_meta',
            ])->where(['post.status' => 2])->leftJoin('author', 'author.id = post.author_id')->all();

        return $this->render('post',
            [
                'post' => $post,
                'id' => $id,
                'post_content' => $post_content,
                'top_post' => $top_post,
                'side_post' => $side_post,
            ]);
    }

    public function actionMore()
    {
        $post = Post::find()->select(
            [
                'post.id',
                'post.author_id',
                'post.title',
                'post.short_description',
                'post.read_time',
                'post.img',
                'post.create_time',
                'post.update_time',
                'post.post_meta',
                'post.status',
                'author.author_name',
                'author.author_pic',
                'author.author_meta',
            ])->leftJoin('author', 'author.id = post.author_id')->orderBy(['post.create_time' => SORT_DESC])->all();

        return $this->render('seemore',
            [
                'post' => $post,
            ]);
    }

    public function actionArchitecture()
    {
        $post = Post::find()->select(
            [
                'post.id',
                'post.author_id',
                'post.title',
                'post.short_description',
                'post.read_time',
                'post.img',
                'post.create_time',
                'post.update_time',
                'post.post_meta',
                'post.status',
                'author.author_name',
                'author.author_pic',
                'author.author_meta',
            ])->where(['post.post_meta' => 'Architecture'])->leftJoin('author', 'author.id = post.author_id')->all();

        $top_post = Post::find()->select(
            [
                'post.id',
                'post.author_id',
                'post.title',
                'post.short_description',
                'post.read_time',
                'post.img',
                'post.create_time',
                'post.update_time',
                'post.post_meta',
                'post.status',
                'author.author_name',
                'author.author_pic',
                'author.author_meta',
            ])->where(['post.status' => 2])->leftJoin('author', 'author.id = post.author_id')->all();

        return $this->render('post-category',
            [
                'post' => $post,
                'top_post' => $top_post,
            ]);
    }

    public function actionRecipes()
    {
        $post = Post::find()->select(
            [
                'post.id',
                'post.author_id',
                'post.title',
                'post.short_description',
                'post.read_time',
                'post.img',
                'post.create_time',
                'post.update_time',
                'post.post_meta',
                'post.status',
                'author.author_name',
                'author.author_pic',
                'author.author_meta',
            ])->where(['post.post_meta' => 'Recipes'])->leftJoin('author', 'author.id = post.author_id')->all();

        $top_post = Post::find()->select(
            [
                'post.id',
                'post.author_id',
                'post.title',
                'post.short_description',
                'post.read_time',
                'post.img',
                'post.create_time',
                'post.update_time',
                'post.post_meta',
                'post.status',
                'author.author_name',
                'author.author_pic',
                'author.author_meta',
            ])->where(['post.status' => 2])->leftJoin('author', 'author.id = post.author_id')->all();

        return $this->render('post-category',
            [
                'post' => $post,
                'top_post' => $top_post,
            ]);
    }

    public function actionPhotography()
    {
        $post = Post::find()->select(
            [
                'post.id',
                'post.author_id',
                'post.title',
                'post.short_description',
                'post.read_time',
                'post.img',
                'post.create_time',
                'post.update_time',
                'post.post_meta',
                'post.status',
                'author.author_name',
                'author.author_pic',
                'author.author_meta',
            ])->where(['post.post_meta' => 'Photography'])->leftJoin('author', 'author.id = post.author_id')->all();

        $top_post = Post::find()->select(
            [
                'post.id',
                'post.author_id',
                'post.title',
                'post.short_description',
                'post.read_time',
                'post.img',
                'post.create_time',
                'post.update_time',
                'post.post_meta',
                'post.status',
                'author.author_name',
                'author.author_pic',
                'author.author_meta',
            ])->where(['post.status' => 2])->leftJoin('author', 'author.id = post.author_id')->all();

        return $this->render('post-category',
            [
                'post' => $post,
                'top_post' => $top_post,
            ]);
    }

    public function actionFeaturedArticle()
    {
        $post = Post::find()->select(
            [
                'post.id',
                'post.author_id',
                'post.title',
                'post.short_description',
                'post.read_time',
                'post.img',
                'post.create_time',
                'post.update_time',
                'post.post_meta',
                'post.status',
                'author.author_name',
                'author.author_pic',
                'author.author_meta',
            ])->where(['post.post_meta' => 'Featured Article'])->leftJoin('author', 'author.id = post.author_id')->all();

        $top_post = Post::find()->select(
            [
                'post.id',
                'post.author_id',
                'post.title',
                'post.short_description',
                'post.read_time',
                'post.img',
                'post.create_time',
                'post.update_time',
                'post.post_meta',
                'post.status',
                'author.author_name',
                'author.author_pic',
                'author.author_meta',
            ])->where(['post.status' => 2])->leftJoin('author', 'author.id = post.author_id')->all();

        return $this->render('post-category',
            [
                'post' => $post,
                'top_post' => $top_post,
            ]);
    }
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model ContactForm */
/* @var $contact SiteController */

use frontend\controllers\SiteController;
use frontend\models\ContactForm;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="inner">
    <div class="section section-gray">
        <div class="section-head">
            <div class="container">
                <h1 class="section-title">Contact Us</h1>
                <div class="section-about">Let us know if you have any questions.</div>
            </div>
        </div>
        <div class="section-body">
            <div class="container">
                <?php $form = ActiveForm::begin(['id' => 'contact-form', 'class' => 'contacts']); ?>
                    <div class="form-group">
                        <label for="Email">Your Email Address</label>
                        <input type="email" class="form-control" id="Email" placeholder="something@website.com" required="">
                    </div>
                    <div class="form-group">
                        <label for="Subject">Subject</label>
                        <input type="email" class="form-control" id="Subject" placeholder="Question about your article" required="">
                    </div>
                    <div class="form-group">
                        <label for="Message">Message</label>
                        <textarea class="form-control" id="Message" placeholder="Your message starts with…" rows="4" required=""></textarea>
                    </div>
                    <div class="form-group">
                        <?= Html::submitButton('Send a Message', ['class' => 'btn btn-primary btn-block', 'name' => 'contact-button']) ?>
                    </div>
                    <?php ActiveForm::end(); ?>
                <div class="center content">
                    <?php foreach ($contact as $block): ?>
                        <?php if ($block->type === 'text'): ?>
                            <?= $block->content ?>
                        <?php endif ?>
                        <?php if ($block->type === 'image-big'): ?>
                            <div class="figure-large">
                                <img src="../images/<?= $block->image ?>"/>
                                <figcaption>
                                    <?= $block->label ?>
                                </figcaption>
                            </div>
                        <?php endif ?>
                        <?php if ($block->type === 'quote'): ?>
                            <blockquote>
                                <?= $block->content ?>
                            </blockquote>
                        <?php endif ?>
                        <?php if ($block->type === 'tip'): ?>
                            <div class="tip">
                                <?= $block->content ?>
                                <img src="../images/<?= $block->image ?>"/>
                                <?= $block->label ?>
                            </div>
                        <?php endif ?>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END inner -->
<!-- END inner -->

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */
/* @var $side_post SiteController */
/* @var $main_post SiteController */
/* @var $top_post SiteController */

$this->title = 'My Blog';

use frontend\controllers\SiteController;
use yii\helpers\Html;
use yii\helpers\Url; ?>

<div class="inner">
    <div class="section section-blog">
        <div class="container">
            <div class="row">
                <?php foreach ($top_post as $item): ?>
                    <div class="col-lg-12 card card-featured card-top">
                        <a class="card-preview"
                           href="<?= Url::to(['post/index']); ?>?id=<?= Html::encode("{$item->id}") ?>">
                            <img class="card-pic" src="images/<?= $item->img ?>" alt="<?= $item->title ?>"/>
                        </a>
                        <div class="card-body">
                            <div class="card-meta"><?= $item->post_meta ?></div>
                            <h2 class="card-title">
                                <a href="<?= Url::to(['post/index']); ?>?id=<?= Html::encode("{$item->id}") ?>"><?= $item->title ?></a>
                            </h2>
                            <div class="card-text"><?= $item->short_description ?>
                            </div>
                            <div class="card-user user">
                                <div class="user-preview">
                                    <img class="user-pic" src="user-pic/<?= $item->author_pic ?>"
                                         alt="<?= $item->author_name ?>"/>
                                </div>
                                <div class="user-wrap">
                                    <div class="user-name"><?= $item->author_name ?></div>
                                    <div class="user-meta"><?= $item->author_meta ?> · <?= $item->read_time ?> min
                                        read
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
                <?php foreach ($main_post as $item): ?>
                    <div class="col-lg-6 card">
                        <a class="card-preview"
                           href="<?= Url::to(['post/index']); ?>?id=<?= Html::encode("{$item->id}") ?>">
                            <img class="card-pic" src="images/<?= $item->img ?>" alt="<?= $item->title ?>"/>
                        </a>
                        <div class="card-body">
                            <div class="card-meta"><?= $item->post_meta ?> · 12 min read</div>
                            <h3 class="card-title">
                                <a href="<?= Url::to(['post/index']); ?>?id=<?= Html::encode("{$item->id}") ?>"><?= $item->title ?></a>
                            </h3>
                            <div class="card-text"><?= $item->short_description ?>
                            </div>
                            <div class="card-user user">
                                <div class="user-preview">
                                    <img class="user-pic" src="user-pic/<?= $item->author_pic ?>"
                                         alt="<?= $item->author_name ?>"/>
                                </div>
                                <div class="user-wrap">
                                    <div class="user-name"><?= $item->author_name ?></div>
                                    <div class="user-meta"><?= $item->author_meta ?></div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
                <?php foreach ($side_post as $item): ?>
                    <div class="col-lg-4 card">
                        <a class="card-preview"
                           href="<?= Url::to(['post/index']); ?>?id=<?= Html::encode("{$item->id}") ?>">
                            <img class="card-pic" src="images/<?= $item->img ?>" alt="<?= $item->title ?>"/>
                        </a>
                        <div class="card-body">
                            <div class="card-meta"><?= $item->post_meta ?> · <?= $item->read_time ?> min read</div>
                            <h3 class="card-title">
                                <a href="<?= Url::to(['post/index']); ?>?id=<?= Html::encode("{$item->id}") ?>"><?= $item->title ?></a>
                            </h3>
                            <div class="card-text"><?= $item->short_description ?>
                            </div>
                            <div class="card-user user">
                                <div class="user-preview">
                                    <img class="user-pic" src="user-pic/<?= $item->author_pic ?>"
                                         alt="<?= $item->author_name ?>"/>
                                </div>
                                <div class="user-wrap">
                                    <div class="user-name"><?= $item->author_name ?></div>
                                    <div class="user-meta"><?= $item->author_meta ?></div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
            <div class="more">
                <?= Html::a('See more posts  ›', ['post/more'], ['class'=>'btn btn-secondary']) ?>
            </div>
        </div>
    </div>
</div>
  

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model LoginForm */

use common\models\LoginForm;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true])->label('Email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                    <br>
                    Need new verification email? <?= Html::a('Resend', ['site/resend-verification-email']) ?>
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model PasswordResetRequestForm */

use frontend\models\PasswordResetRequestForm;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resendVerificationEmail.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model ResetPasswordForm */

use frontend\models\ResetPasswordForm;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Resend verification email';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-resend-verification-email">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A verification email will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'resend-verification-email-form']); ?>

            <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

            <div class="form-group">
                <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model ResetPasswordForm */

use frontend\models\ResetPasswordForm;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model SignupForm */

use frontend\models\SignupForm;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/terms.php
<?php

/* @var $this yii\web\View */

/* @var $terms SiteController */

use frontend\controllers\SiteController;

$this->title = 'Terms';

?>
<div class="inner">
    <div class="section">
        <div class="section-head">
            <div class="container">
                <h1 class="section-title">Terms of Services</h1>
            </div>
        </div>
        <div class="section-body">
            <div class="container">
                <div class="center content">
                    <?php foreach ($terms as $block): ?>
                        <?php if ($block->type === 'text'): ?>
                            <?= $block->content ?>
                        <?php endif ?>
                        <?php if ($block->type === 'image-big'): ?>
                            <div class="figure-large">
                                <img src="../images/<?= $block->image ?>"/>
                                <figcaption>
                                    <?= $block->label ?>
                                </figcaption>
                            </div>
                        <?php endif ?>
                        <?php if ($block->type === 'quote'): ?>
                            <blockquote>
                                <?= $block->content ?>
                            </blockquote>
                        <?php endif ?>
                        <?php if ($block->type === 'tip'): ?>
                            <div class="tip">
                                <?= $block->content ?>
                                <img src="../images/<?= $block->image ?>"/>
                                <?= $block->label ?>
                            </div>
                        <?php endif ?>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>